[project]
name = "mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.67.0",
    "asyncio>=4.0.0",
    "dotenv>=0.9.9",
    "mcp>=1.14.0",
]
